<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Http\Requests;

class CoordsController extends Controller
{
	// public function __construct()
 //    {
 //        $this->middleware('auth');
 //    }
	
	public function create()
	{
	    
	    $u = "coord[nome]=".$_POST['nome']."&coord[email]=".$_POST['email']."&usuarioid=4";
	    ///echo "$u";
	    
	    $ch = curl_init();

	    curl_setopt($ch, CURLOPT_URL, "eventos-gleidsonxd.c9users.io/coords");
	    curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
	    curl_setopt($ch, CURLOPT_POSTFIELDS, "$u");
	    curl_setopt($ch, CURLOPT_POST, 1);

	    $result = curl_exec($ch);
	    if (curl_errno($ch)) {
	        echo 'Error:' . curl_error($ch);
	    }
	    curl_close ($ch);
	    return view("index");
		
	}

	public function listAll()
	{
		$u = "?usuarioid=4";
	   
	    $ch = curl_init();

	    curl_setopt($ch, CURLOPT_URL, "eventos-gleidsonxd.c9users.io/coords".$u);
	    curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
	   // curl_setopt($ch, CURLOPT_POSTFIELDS, "usuarioid=4");
	  //  curl_setopt($ch, CURLOPT_CUSTOMREQUEST, "GET");


	    $result = curl_exec($ch);
	   
	    if (curl_errno($ch)) {
	        echo 'Error:' . curl_error($ch);
	    }
	    curl_close ($ch);
	    
		// $pessoas = pessoa::All();
		
		return view('coords', array('result' => $result));
	}

	public function read($id)
	{
		$u = "?usuarioid=4";
	    $ch = curl_init();
	    curl_setopt($ch, CURLOPT_URL, "eventos-gleidsonxd.c9users.io/coords/".$id.$u);
	    curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
	    // curl_setopt($ch, CURLOPT_POSTFIELDS, "usuarioid=4");
	    // curl_setopt($ch, CURLOPT_CUSTOMREQUEST, "GET");


	    $result = curl_exec($ch);
	   // echo $result;
	    if (curl_errno($ch)) {
	        echo 'Error:' . curl_error($ch);
	    }
	    curl_close ($ch);
		// $pessoa = pessoa::find($id);
	    return view("coordU", array('result' => $result));
	}

	public function edit()
	{
	   $id = $_POST['coordid'];
	   $ch = curl_init();
	    curl_setopt($ch, CURLOPT_URL, "eventos-gleidsonxd.c9users.io/coords/".$id);
	    curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
	    curl_setopt($ch, CURLOPT_POSTFIELDS, "usuarioid=4");
	    curl_setopt($ch, CURLOPT_CUSTOMREQUEST, "GET");


	    $result = curl_exec($ch);
	   // echo $result;
	    if (curl_errno($ch)) {
	        echo 'Error:' . curl_error($ch);
	    }
	    curl_close ($ch);
	    // $pessoa = pessoa::find($id);
	        return view("coord_edit", array('result' => $result));
	}

	public function update($id)
	{
	   
		
	// Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
	    $ch = curl_init();

	    $u = "coord[nome]=".$_POST['nome']."&coord[email]=".$_POST['email']."&usuarioid=4";

	    curl_setopt($ch, CURLOPT_URL, "eventos-gleidsonxd.c9users.io/coords/".$id);
	    curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
	    curl_setopt($ch, CURLOPT_POSTFIELDS, "$u");
	    curl_setopt($ch, CURLOPT_CUSTOMREQUEST, "PUT");


	    $result = curl_exec($ch);
	    if (curl_errno($ch)) {
	        echo 'Error:' . curl_error($ch);
	    }else{
	    	echo $result;
	    }
	    curl_close ($ch);

	    echo "<br><br><a href='/'>Volta</a>";


	}

	public function delete($id)
	{
	    
		
	    // Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
	    $ch = curl_init();

	    curl_setopt($ch, CURLOPT_URL, "eventos-gleidsonxd.c9users.io/coords/".$id);
	    curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
	    curl_setopt($ch, CURLOPT_POSTFIELDS, "usuarioid=4");
	    curl_setopt($ch, CURLOPT_CUSTOMREQUEST, "DELETE");


	    $result = curl_exec($ch);
	    if (curl_errno($ch)) {
	        echo 'Error:' . curl_error($ch);
	    }else{
	    	echo $result;
	    }
	    curl_close ($ch);
	    echo "<br><br><a href='/'>Volta</a>";
	}
	
}
