<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Http\Requests;

class EventosController extends Controller
{
    public function form()
    {
    	$ch = curl_init();

	    curl_setopt($ch, CURLOPT_URL, "eventos-gleidsonxd.c9users.io/servicos");
	    curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
	    curl_setopt($ch, CURLOPT_POSTFIELDS, "usuarioid=4");
	    curl_setopt($ch, CURLOPT_CUSTOMREQUEST, "GET");


	    $results = curl_exec($ch);
	   
	    if (curl_errno($ch)) {
	        echo 'Error:' . curl_error($ch);
	    }
	    curl_close ($ch);
	    

    	
	   	$ch = curl_init();
	    curl_setopt($ch, CURLOPT_URL, "eventos-gleidsonxd.c9users.io/lugars");
	    curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
	    curl_setopt($ch, CURLOPT_POSTFIELDS, "usuarioid=4");
	    curl_setopt($ch, CURLOPT_CUSTOMREQUEST, "GET");


	    $resultl = curl_exec($ch);
	   // echo $result;
	    if (curl_errno($ch)) {
	        echo 'Error:' . curl_error($ch);
	    }
	    curl_close ($ch);
	    // $pessoa = pessoa::find($id);
	        return view("evento_form", compact('results', 'resultl'));	
    }
    public function create()
     {	
     	if (isset($_POST['servicos'])) {
     		$aS = $_POST['servicos'];
    		$s = implode(",", $aS);
     	}else{
     		$s = '';
     	}
     	if (isset($_POST['lugares'])) {
     		$aL = $_POST['lugares'];
    		$l = implode(",", $aL);
     	}else{
     		$l='';
     	}

    	
    	//echo $s;
    	
    	
    	$u = "evento[nome]=".$_POST['nome']."&evento[data_ini]=".$_POST['data_ini']."&evento[data_fim]=".$_POST['data_fim']."&evento[descricao]=".$_POST['desc']."&servicos=".$s."&lugares=".$l."&evento[usuario_id]=4";
    	//echo "$u";
		// // Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
		$ch = curl_init();

		curl_setopt($ch, CURLOPT_URL, "eventos-gleidsonxd.c9users.io/eventos");
		curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
		curl_setopt($ch, CURLOPT_POSTFIELDS, "$u");
		curl_setopt($ch, CURLOPT_POST, 1);

		$result = curl_exec($ch);
		if (curl_errno($ch)) {
		    echo 'Error:' . curl_error($ch);
		}
		curl_close ($ch);
		return view("index");
    }
    public function listAll()
    {
    	$ch = curl_init();

		curl_setopt($ch, CURLOPT_URL, "eventos-gleidsonxd.c9users.io/eventos");
		curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
	//	curl_setopt($ch, CURLOPT_POSTFIELDS, "usuarioid=4");
		//curl_setopt($ch, CURLOPT_CUSTOMREQUEST, "GET");


		$result = curl_exec($ch);
		if (curl_errno($ch)) {
		    echo 'Error:' . curl_error($ch);
		}
		curl_close ($ch);
		return view('eventos', array('result' => $result));
    }
    public function read($id)
    {
    	$ch = curl_init();

		curl_setopt($ch, CURLOPT_URL, "eventos-gleidsonxd.c9users.io/eventos/".$id);
		curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
		// curl_setopt($ch, CURLOPT_POSTFIELDS, "usuarioid=4");
		// curl_setopt($ch, CURLOPT_CUSTOMREQUEST, "GET");


		$result = curl_exec($ch);
		if (curl_errno($ch)) {
		    echo 'Error:' . curl_error($ch);
		}
		curl_close ($ch);
		//var_dump(json_decode($result,true));
		
		
		return view('eventoU', array('result' => $result));
    }
    public function edit()
    {
    	$ch = curl_init();

	    curl_setopt($ch, CURLOPT_URL, "eventos-gleidsonxd.c9users.io/servicos");
	    curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
	    curl_setopt($ch, CURLOPT_POSTFIELDS, "usuarioid=4");
	    curl_setopt($ch, CURLOPT_CUSTOMREQUEST, "GET");


	    $results = curl_exec($ch);
	   
	    if (curl_errno($ch)) {
	        echo 'Error:' . curl_error($ch);
	    }
	    curl_close ($ch);
	    

    	
	   	$ch = curl_init();
	    curl_setopt($ch, CURLOPT_URL, "eventos-gleidsonxd.c9users.io/lugars");
	    curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
	    curl_setopt($ch, CURLOPT_POSTFIELDS, "usuarioid=4");
	    curl_setopt($ch, CURLOPT_CUSTOMREQUEST, "GET");


	    $resultl = curl_exec($ch);
	   // echo $result;
	    if (curl_errno($ch)) {
	        echo 'Error:' . curl_error($ch);
	    }
	    curl_close ($ch);
	    // $pessoa = pessoa::find($id);

	    $id = $_POST['eventoid'];
	    $ch = curl_init();

		curl_setopt($ch, CURLOPT_URL, "eventos-gleidsonxd.c9users.io/eventos/".$id);
		curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
		// curl_setopt($ch, CURLOPT_POSTFIELDS, "usuarioid=4");
		// curl_setopt($ch, CURLOPT_CUSTOMREQUEST, "GET");


		$result = curl_exec($ch);
		if (curl_errno($ch)) {
		    echo 'Error:' . curl_error($ch);
		}
		curl_close ($ch);


	    return view("evento_edit", compact('results', 'resultl','result'));	
    }
    public function update($id)
    {
    	$u = "evento[nome]=".$_POST['nome']."&evento[data_ini]=".$_POST['data_ini']."&evento[data_fim]=".$_POST['data_fim']."&evento[descricao]=".$_POST['desc']."&evento[usuario_id]=4&usuarioid=4";
    	$ch = curl_init();

	    curl_setopt($ch, CURLOPT_URL, "eventos-gleidsonxd.c9users.io/eventos/".$id);
	    curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
	    curl_setopt($ch, CURLOPT_POSTFIELDS, "$u");
	    curl_setopt($ch, CURLOPT_CUSTOMREQUEST, "PUT");


	    $result = curl_exec($ch);
	    if (curl_errno($ch)) {
	        echo 'Error:' . curl_error($ch);
	    }else{
	    	echo $result;
	    }
	    curl_close ($ch);

	    echo "<br><br><a href='/'>Volta</a>";
    }
    public function delete($id)
    {
    	// Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
	    $ch = curl_init();

	    curl_setopt($ch, CURLOPT_URL, "eventos-gleidsonxd.c9users.io/eventos/".$id);
	    curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
	    curl_setopt($ch, CURLOPT_POSTFIELDS, "usuarioid=4");
	    curl_setopt($ch, CURLOPT_CUSTOMREQUEST, "DELETE");


	    $result = curl_exec($ch);
	    if (curl_errno($ch)) {
	        echo 'Error:' . curl_error($ch);
	    }else{
	    	echo $result;
	    }
	    curl_close ($ch);
	    echo "<br><br><a href='/'>Volta</a>";
    }

    public function feed()
    {

    	$ch = curl_init();

		curl_setopt($ch, CURLOPT_URL, "eventos-gleidsonxd.c9users.io/eventos");
		curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
	//	curl_setopt($ch, CURLOPT_POSTFIELDS, "usuarioid=4");
		//curl_setopt($ch, CURLOPT_CUSTOMREQUEST, "GET");


		$result = curl_exec($ch);
		if (curl_errno($ch)) {
		    echo 'Error:' . curl_error($ch);
		}
		curl_close ($ch);
		$feed = array();
		$eventos = json_decode($result);
		foreach ($eventos as $e) {
			$feed[] = [
				'id' => $e->id,
				'title' => $e->nome,
				'start' => $e->data_ini,
				'end' =>   $e->data_fim,
				'url' => "/eventos/".$e->id,
				'color'=> "green"
			];
			
		}


		
		return response()->json($feed);
    }

}
