<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Http\Requests;

class LugarsController extends Controller
{
    public function form()
    {
    	if (session('logado')!= 1){
		return view("mlogin");
		}
		if (session('adm') == false){
		return view("noadmin");
		}
    	return view('lugar_form');
    }
    public function create()
    {
    	if (session('logado')!= 1){
		return view("mlogin");
		}
		if (session('adm') == false){
		return view("noadmin");
		}
		$idu = session('id');
		if (isset($idu)){
			$u = "lugar[nome]=".$_POST['nome']."&lugar[quantidade]=".$_POST['quantidade']."&usuarioid=".$idu;
		}
    	 ///echo "$u";
		// Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
		$ch = curl_init();

		curl_setopt($ch, CURLOPT_URL, env('CONSTANT')."/lugars");
		curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
		curl_setopt($ch, CURLOPT_HTTPAUTH, CURLAUTH_ANY); 
		curl_setopt($ch, CURLOPT_USERPWD, env('USERPWD'));
		curl_setopt($ch, CURLOPT_POSTFIELDS, "$u");
		curl_setopt($ch, CURLOPT_POST, 1);

		$result = curl_exec($ch);
		if (curl_errno($ch)) {
		    echo 'Error:' . curl_error($ch);
		    return view('lugareors',array('erro'=>"Ocorreu um erro ao criar o Lugar!"));
		}else{
	    	return view('lugareors',array('sucesso'=>"Lugar criado com sucesso!"));
	    }
		curl_close ($ch);
		/*return view("index");*/

    }
	public function listAll()
	{	
		if (session('logado')!= 1){
		return view("mlogin");
		}
		if (session('adm') == false){
		return view("noadmin");
		}
		// Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
		$idu = session('id');
		if (isset($idu)){
			$u = "?usuarioid=".$idu;
		}
		$ch = curl_init();

		curl_setopt($ch, CURLOPT_URL, env('CONSTANT')."/lugars".$u);
		curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
		curl_setopt($ch, CURLOPT_HTTPAUTH, CURLAUTH_ANY); 
		curl_setopt($ch, CURLOPT_USERPWD, env('USERPWD'));
		
		$result = curl_exec($ch);
		if (curl_errno($ch)) {
		    echo 'Error:' . curl_error($ch);
		}
		curl_close ($ch);
		return view('lugars', array('result' => $result));
	}
	public function read($id)
	{	
		if (session('logado')!= 1){
		return view("mlogin");
		}
		if (session('adm') == false){
		return view("noadmin");
		}
		// Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
		$idu = session('id');
		if (isset($idu)){
			$u = "?usuarioid=".$idu;
		}
		$ch = curl_init();
		
		curl_setopt($ch, CURLOPT_URL, env('CONSTANT')."/lugars/".$id.$u);
		curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
		curl_setopt($ch, CURLOPT_HTTPAUTH, CURLAUTH_ANY); 
		curl_setopt($ch, CURLOPT_USERPWD, env('USERPWD'));
		


		$result = curl_exec($ch);
		if (curl_errno($ch)) {
		    echo 'Error:' . curl_error($ch);
		}
		curl_close ($ch);
		return view('lugarU', array('result' => $result));
	}
	public function edit()
	{
		if (session('logado')!= 1){
		return view("mlogin");
		}
		if (session('adm') == false){
		return view("noadmin");
		}
		$id = $_POST['lugarid'];
		$idu = session('id');
		if (isset($idu)){
			$u = "?usuarioid=".$idu;
		}
	   	$ch = curl_init();
	    curl_setopt($ch, CURLOPT_URL, env('CONSTANT')."/lugars/".$id.$u);
	    curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
	    curl_setopt($ch, CURLOPT_HTTPAUTH, CURLAUTH_ANY); 
		curl_setopt($ch, CURLOPT_USERPWD, env('USERPWD'));
	    
	    $result = curl_exec($ch);
	   // echo $result;
	    if (curl_errno($ch)) {
	        echo 'Error:' . curl_error($ch);
	    }
	    curl_close ($ch);
	    // $pessoa = pessoa::find($id);
	        return view("lugar_edit", array('result' => $result));
	}
	public function update($id)
	{
		if (session('logado')!= 1){
		return view("mlogin");
		}
		if (session('adm') == false){
		return view("noadmin");
		}
		$idu = session('id');
		if (isset($idu)){
			$u = "lugar[nome]=".$_POST['nome']."&lugar[quantidade]=".$_POST['quantidade']."&usuarioid=".$idu;
		}
		
		// Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
	    $ch = curl_init();

	    curl_setopt($ch, CURLOPT_URL, env('CONSTANT')."/lugars/".$id);
	    curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
	    curl_setopt($ch, CURLOPT_HTTPAUTH, CURLAUTH_ANY); 
		curl_setopt($ch, CURLOPT_USERPWD, env('USERPWD'));
	    curl_setopt($ch, CURLOPT_POSTFIELDS, "$u");
	    curl_setopt($ch, CURLOPT_CUSTOMREQUEST, "PUT");


	    $result = curl_exec($ch);
	    if (curl_errno($ch)) {
	        echo 'Error:' . curl_error($ch);
	        return view('lugareors',array('erro'=>"Ocorreu um erro ao editar o Lugar!"));
	    }else{
	    	//$sucesso = array('sucesso' =>"Lugar editado com sucesso!");
	    	//echo $result;
	    	return view('lugareors', array('result' => $result))->with('sucesso', "Lugar editado com sucesso!");
	    }
	    curl_close ($ch);

	}
	public function delete($id)
	{
		if (session('logado')!= 1){
		return view("mlogin");
		}
		if (session('adm') == false){
		return view("noadmin");
		}
		$idu = session('id');
		if (isset($idu)){
			$u = "?usuarioid=".$idu;
		}
	    // Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
	    $ch = curl_init();

	    curl_setopt($ch, CURLOPT_URL, env('CONSTANT')."/lugars/".$id.$u);
	    curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
	    curl_setopt($ch, CURLOPT_HTTPAUTH, CURLAUTH_ANY); 
		curl_setopt($ch, CURLOPT_USERPWD, env('USERPWD'));
	    curl_setopt($ch, CURLOPT_CUSTOMREQUEST, "DELETE");


	    $result = curl_exec($ch);
	    if (curl_errno($ch)) {
	        echo 'Error:' . curl_error($ch);
	        return view('lugareors',array('erro'=>"Ocorreu um erro ao remover o Lugar!"));
	    }else{
	    	return view('lugareors',array('sucesso'=>"Lugar removido com sucesso!"));
	    }
	    curl_close ($ch);
	    
	}

}
