<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Http\Requests;

class ServicosController extends Controller
{
	public function __construct()
    {
        $this->middleware('auth');
    }

	public function form()
	{

	    $ch = curl_init();

	    curl_setopt($ch, CURLOPT_URL, "eventos-gleidsonxd.c9users.io/coords");
	    curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
	    curl_setopt($ch, CURLOPT_POSTFIELDS, "usuarioid=4");
	    curl_setopt($ch, CURLOPT_CUSTOMREQUEST, "GET");


	    $result = curl_exec($ch);
	   
	    if (curl_errno($ch)) {
	        echo 'Error:' . curl_error($ch);
	    }
	    curl_close ($ch);
	    
		return view('servico_form', array('result' => $result));
	}
    public function create()
    {

    	$u = "servico[nome]=".$_POST['nome']."&servico[tempo]=".$_POST['tempo']."&servico[coord_id]=".$_POST['coord']."&usuarioid="."4";
    	
    	 ///echo "$u";
		// Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
		$ch = curl_init();

		curl_setopt($ch, CURLOPT_URL, "eventos-gleidsonxd.c9users.io/servicos");
		curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
		curl_setopt($ch, CURLOPT_POSTFIELDS, "$u");
		curl_setopt($ch, CURLOPT_POST, 1);

		$result = curl_exec($ch);
		if (curl_errno($ch)) {
		    echo 'Error:' . curl_error($ch);
		}
		curl_close ($ch);
		return view("index");
    }
    public function listAll()
    {
   
    	// Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
		$ch = curl_init();

		curl_setopt($ch, CURLOPT_URL, "eventos-gleidsonxd.c9users.io/servicos");
		curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
		curl_setopt($ch, CURLOPT_POSTFIELDS, "usuarioid=4");
		curl_setopt($ch, CURLOPT_CUSTOMREQUEST, "GET");


		$result = curl_exec($ch);
		if (curl_errno($ch)) {
		    echo 'Error:' . curl_error($ch);
		}
		curl_close ($ch);
		return view('servicos', array('result' => $result));
    }
    public function read($id)
    {
    	
		$ch = curl_init();

		curl_setopt($ch, CURLOPT_URL, "eventos-gleidsonxd.c9users.io/servicos/".$id);
		curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
		curl_setopt($ch, CURLOPT_POSTFIELDS, "usuarioid=4");
		curl_setopt($ch, CURLOPT_CUSTOMREQUEST, "GET");


		$result = curl_exec($ch);
		if (curl_errno($ch)) {
		    echo 'Error:' . curl_error($ch);
		}
		curl_close ($ch);
		//var_dump(json_decode($result,true));
		
		
		return view('servicoU', array('result' => $result));
    }
    public function edit()
    {
    	$ch = curl_init();

	    curl_setopt($ch, CURLOPT_URL, "eventos-gleidsonxd.c9users.io/coords");
	    curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
	    curl_setopt($ch, CURLOPT_POSTFIELDS, "usuarioid=4");
	    curl_setopt($ch, CURLOPT_CUSTOMREQUEST, "GET");


	    $resultC = curl_exec($ch);
	   
	    if (curl_errno($ch)) {
	        echo 'Error:' . curl_error($ch);
	    }
	    curl_close ($ch);
	    

    	$id = $_POST['servicoid'];
	   	$ch = curl_init();
	    curl_setopt($ch, CURLOPT_URL, "eventos-gleidsonxd.c9users.io/servicos/".$id);
	    curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
	    curl_setopt($ch, CURLOPT_POSTFIELDS, "usuarioid=4");
	    curl_setopt($ch, CURLOPT_CUSTOMREQUEST, "GET");


	    $result = curl_exec($ch);
	   // echo $result;
	    if (curl_errno($ch)) {
	        echo 'Error:' . curl_error($ch);
	    }
	    curl_close ($ch);
	    // $pessoa = pessoa::find($id);
	        return view("servico_edit", compact('result', 'resultC'));	
    }
    public function update($id)
    {
    	$u = "servico[nome]=".$_POST['nome']."&servico[tempo]=".$_POST['tempo']."&servico[coord_id]=".$_POST['coord']."&usuarioid="."4";
    	 $ch = curl_init();

	    curl_setopt($ch, CURLOPT_URL, "eventos-gleidsonxd.c9users.io/servicos/".$id);
	    curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
	    curl_setopt($ch, CURLOPT_POSTFIELDS, "$u");
	    curl_setopt($ch, CURLOPT_CUSTOMREQUEST, "PUT");


	    $result = curl_exec($ch);
	    if (curl_errno($ch)) {
	        echo 'Error:' . curl_error($ch);
	    }else{
	    	echo $result;
	    }
	    curl_close ($ch);

	    echo "<br><br><a href='/'>Volta</a>";
    }
    public function delete($id)
    {
    	// Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
	    $ch = curl_init();

	    curl_setopt($ch, CURLOPT_URL, "eventos-gleidsonxd.c9users.io/servicos/".$id);
	    curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
	    curl_setopt($ch, CURLOPT_POSTFIELDS, "usuarioid=4");
	    curl_setopt($ch, CURLOPT_CUSTOMREQUEST, "DELETE");


	    $result = curl_exec($ch);
	    if (curl_errno($ch)) {
	        echo 'Error:' . curl_error($ch);
	    }else{
	    	echo $result;
	    }
	    curl_close ($ch);
	    echo "<br><br><a href='/'>Volta</a>";
    }
}
