<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Http\Requests;

class UsuariosController extends Controller
{
    public function create()
    {
    	
    	//$u = "usuario[nome]=".$_POST['nome']."&usuario[email]=".$_POST['email'].."&usuario[matricula]=".$_POST['matricula']."&usuarioid="."4";
    	$u = "usuario[nome]=".$_POST['nome']."&usuario[email]=".$_POST['email']."&usuario[matricula]=".$_POST['matricula'];
    	 ///echo "$u";
		// Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
		$ch = curl_init();

		curl_setopt($ch, CURLOPT_URL, "eventos-gleidsonxd.c9users.io/usuarios");
		curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
		curl_setopt($ch, CURLOPT_POSTFIELDS, "$u");
		curl_setopt($ch, CURLOPT_POST, 1);

		$result = curl_exec($ch);
		if (curl_errno($ch)) {
		    echo 'Error:' . curl_error($ch);
		}
		curl_close ($ch);
		return view("index");
    }
    public function listAll()
    {
    	// Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
		$ch = curl_init();

		curl_setopt($ch, CURLOPT_URL, "eventos-gleidsonxd.c9users.io/usuarios");
		curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
		// curl_setopt($ch, CURLOPT_POSTFIELDS, "usuarioid=4");
		// curl_setopt($ch, CURLOPT_CUSTOMREQUEST, "GET");


		$result = curl_exec($ch);
		if (curl_errno($ch)) {
		    echo 'Error:' . curl_error($ch);
		}
		curl_close ($ch);
		return view('usuarios', array('result' => $result));
    }
    public function read($id)
    {
    	// Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
		$ch = curl_init();

		curl_setopt($ch, CURLOPT_URL, "eventos-gleidsonxd.c9users.io/usuarios/".$id);
		curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
		// curl_setopt($ch, CURLOPT_POSTFIELDS, "usuarioid=4");
		// curl_setopt($ch, CURLOPT_CUSTOMREQUEST, "GET");


		$result = curl_exec($ch);
		if (curl_errno($ch)) {
		    echo 'Error:' . curl_error($ch);
		}
		curl_close ($ch);
		return view('usuarioU', array('result' => $result));
    }
    public function edit()
    {
    	$id = $_POST['usuarioid'];
	   	$ch = curl_init();
	    curl_setopt($ch, CURLOPT_URL, "eventos-gleidsonxd.c9users.io/usuarios/".$id);
	    curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
	    // curl_setopt($ch, CURLOPT_POSTFIELDS, "usuarioid=4");
	    // curl_setopt($ch, CURLOPT_CUSTOMREQUEST, "GET");


	    $result = curl_exec($ch);
	   // echo $result;
	    if (curl_errno($ch)) {
	        echo 'Error:' . curl_error($ch);
	    }
	    curl_close ($ch);
	    // $pessoa = pessoa::find($id);
	        return view("usuario_edit", array('result' => $result));
    }
    public function update($id)
    {
    	//$u = "usuario[nome]=".$_POST['nome']."&usuario[email]=".$_POST['email'].."&usuario[matricula]=".$_POST['matricula']."&usuarioid="."4";
    	$u = "usuario[nome]=".$_POST['nome']."&usuario[email]=".$_POST['email']."&usuario[matricula]=".$_POST['matricula'];
    	 $ch = curl_init();

	    curl_setopt($ch, CURLOPT_URL, "eventos-gleidsonxd.c9users.io/usuarios/".$id);
	    curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
	    curl_setopt($ch, CURLOPT_POSTFIELDS, "$u");
	    curl_setopt($ch, CURLOPT_CUSTOMREQUEST, "PUT");


	    $result = curl_exec($ch);
	    if (curl_errno($ch)) {
	        echo 'Error:' . curl_error($ch);
	    }else{
	    	echo $result;
	    }
	    curl_close ($ch);

	    echo "<br><br><a href='/'>Volta</a>";
    }
    public function delete($id)
    {
    	// Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
	    $ch = curl_init();

	    curl_setopt($ch, CURLOPT_URL, "eventos-gleidsonxd.c9users.io/usuarios/".$id);
	    curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
	   // curl_setopt($ch, CURLOPT_POSTFIELDS, "usuarioid=4");
	    curl_setopt($ch, CURLOPT_CUSTOMREQUEST, "DELETE");


	    $result = curl_exec($ch);
	    if (curl_errno($ch)) {
	        echo 'Error:' . curl_error($ch);
	    }else{
	    	echo $result;
	    }
	    curl_close ($ch);
	    echo "<br><br><a href='/'>Volta</a>";
    }
  //   public function login()
  //   {
  //   	$e = $_POST['email'];

  //   	$ch = curl_init();

		// curl_setopt($ch, CURLOPT_URL, "eventos-gleidsonxd.c9users.io/usuarios");
		// curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
		// // curl_setopt($ch, CURLOPT_POSTFIELDS, "usuarioid=4");
		// // curl_setopt($ch, CURLOPT_CUSTOMREQUEST, "GET");


		// $result = curl_exec($ch);
		// if (curl_errno($ch)) {
		//     echo 'Error:' . curl_error($ch);
		// }
		// curl_close ($ch);

		// $usuarios = json_decode($result);
		// foreach ($usuarios as $u) {
		// 	if ($u->email == $e) {
		// 		session(['email' => $u->email]);
		// 		session(['id' => $u->id]);
  //   			session(['logado' => true]);
		// 	}
		// 	else{
		// 		session(['logado' => false]);
		// 	}
		// }
		// return view("index");
  //   }

  //   public function logout(Request $req)
  //   {

  //   	$req->session()->flush();
  //   	return view("\mlogin");
  //   }
}
