<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Http\Requests;

class UsuariosController extends Controller
{
	public function form()
	{
		$email = session('email');
    	if (!isset($email)){
		return view("mlogin");
		}
		
		return view('usuario_form');
	}
    public function create()
    {	
    
    	$email = session('email');
    	if (!isset($email)){
		return view("mlogin");
		}
		// if (session('adm') == false){
		// return view("noadmin");
		// }
		
    	//$u = "usuario[nome]=".$_POST['nome']."&usuario[email]=".$_POST['email'].."&usuario[matricula]=".$_POST['matricula']."&usuarioid="."4";
    	$u = "usuario[nome]=".$_POST['nome']."&usuario[email]=".$_POST['email']."&usuario[matricula]=".$_POST['matricula'];
    	 ///echo "$u";
		// Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
		$ch = curl_init();

		curl_setopt($ch, CURLOPT_URL, "eventos-gleidsonxd.c9users.io/usuarios");
		curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
		curl_setopt($ch, CURLOPT_POSTFIELDS, "$u");
		curl_setopt($ch, CURLOPT_POST, 1);

		$result = curl_exec($ch);
		if (curl_errno($ch)) {
		    echo 'Error:' . curl_error($ch);
		}
		curl_close ($ch);
		return view("index");
    }
    public function listAll()
    {
    	if (session('logado')!= 1){
		return view("mlogin");
		}
		if (session('adm') == false){
		return view("noadmin");
		}
		$idu = session('id');
		if (isset($idu)){
			$u = "?usuarioid=".$idu;
		}
    	// Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
    	
		$ch = curl_init();

		curl_setopt($ch, CURLOPT_URL, "eventos-gleidsonxd.c9users.io/usuarios".$u);
		curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
		


		$result = curl_exec($ch);
		if (curl_errno($ch)) {
		    echo 'Error:' . curl_error($ch);
		}
		curl_close ($ch);
		return view('usuarios', array('result' => $result));
    }
    public function read($id) #ADMIN OU OWNER
    {
    	if (session('logado')!= 1){
		return view("mlogin");
		}
		if (session('adm') == false){
		return view("noadmin");
		}
		$idu = session('id');
		if (isset($idu)){
			$u = "?usuarioid=".$idu;
		}
    	// Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
		$ch = curl_init();

		curl_setopt($ch, CURLOPT_URL, "eventos-gleidsonxd.c9users.io/usuarios/".$id.$u);
		curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
		


		$result = curl_exec($ch);
		if (curl_errno($ch)) {
		    echo 'Error:' . curl_error($ch);
		}
		curl_close ($ch);
		return view('usuarioU', array('result' => $result));
    }
    public function edit()#ADMIN OU OWNER
    {
    	if (session('logado')!= 1){
		return view("mlogin");
		}
		if (session('adm') == false){
		return view("noadmin");
		}
		$idu = session('id');
		if (isset($idu)){
			$u = "?usuarioid=".$idu;
		}
    	$id = $_POST['usuarioid'];
	   	$ch = curl_init();
	    curl_setopt($ch, CURLOPT_URL, "eventos-gleidsonxd.c9users.io/usuarios/".$id.$u);
	    curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
	    


	    $result = curl_exec($ch);
	   // echo $result;
	    if (curl_errno($ch)) {
	        echo 'Error:' . curl_error($ch);
	    }
	    curl_close ($ch);
	    // $pessoa = pessoa::find($id);
	        return view("usuario_edit", array('result' => $result));
    }
    public function update($id)#ADMIN OU OWNER
    {
    	if (session('logado')!= 1){
		return view("mlogin");
		}
		if (session('adm') == false){
		return view("noadmin");
		}
		$idu = session('id');
		if (isset($idu)){
			$u = "usuario[nome]=".$_POST['nome']."&usuario[email]=".$_POST['email']."&usuario[matricula]=".$_POST['matricula']."&usuarioid=".$idu;
		}
    	//$u = "usuario[nome]=".$_POST['nome']."&usuario[email]=".$_POST['email']."&usuario[matricula]=".$_POST['matricula']."&usuarioid="."4";
    //	$u = "usuario[nome]=".$_POST['nome']."&usuario[email]=".$_POST['email']."&usuario[matricula]=".$_POST['matricula'];
    	 $ch = curl_init();

	    curl_setopt($ch, CURLOPT_URL, "eventos-gleidsonxd.c9users.io/usuarios/".$id);
	    curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
	    curl_setopt($ch, CURLOPT_POSTFIELDS, "$u");
	    curl_setopt($ch, CURLOPT_CUSTOMREQUEST, "PUT");


	    $result = curl_exec($ch);
	    if (curl_errno($ch)) {
	        echo 'Error:' . curl_error($ch);
	    }else{
	    	echo $result;
	    }
	    curl_close ($ch);

	    echo "<br><br><a href='/index'>Volta</a>";
    }
    public function delete($id)
    {
    	if (session('logado')!= 1){
		return view("mlogin");
		}
		if (session('adm') == false){
		return view("noadmin");
		}
		$idu = session('id');
		if (isset($idu)){
			$u = "?usuarioid=".$idu;
		}
    	// Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
	    $ch = curl_init();

	    curl_setopt($ch, CURLOPT_URL, "eventos-gleidsonxd.c9users.io/usuarios/".$id.$u);
	    curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
	    curl_setopt($ch, CURLOPT_CUSTOMREQUEST, "DELETE");


	    $result = curl_exec($ch);
	    if (curl_errno($ch)) {
	        echo 'Error:' . curl_error($ch);
	    }else{
	    	echo $result;
	    }
	    curl_close ($ch);
	    echo "<br><br><a href='/index'>Volta</a>";
    }
     public function login()
     {
     	$e = $_POST['email'];

     	
		// Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
		$ch = curl_init();
		
		curl_setopt($ch, CURLOPT_URL, "eventos-gleidsonxd.c9users.io/login");
		curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
		curl_setopt($ch, CURLOPT_POSTFIELDS, "email=".$e);
		curl_setopt($ch, CURLOPT_POST, 1);
		
		$result = curl_exec($ch);
		if (curl_errno($ch)) {
		    echo 'Error:' . curl_error($ch);
		}
		curl_close ($ch);
		$res = json_decode($result);
		
	
		if (@$res->logado == 1) {
			$email = @$res->email;
			$id = @$res->id;
			$logado = @$res->logado;
			$adm = @$res->adm;
			if ($adm != 1) {
				session(['adm' => 0]);
			}else{
				session(['adm' => 1]);
			}
			session(['email' => $email]);
			session(['logado' => $logado]);
			session(['id' => $id]);
			
		}else{
			
			session(['email' => $e]);
			session(['pri' => true]);
			return view("usuarionovo");
		}
		//	echo session('adm') ;
		return view("eventos");
		
     }

     public function logout(Request $req)
     {

     	$req->session()->flush();
     	return view("mlogin");
     }
}
